// client/src/routes/signup/+page.svelte
<script>
  import FormField from '$lib/components/FormField.svelte';
  import Alert from '$lib/components/Alert.svelte';
  import { AlertType } from '$lib/constants/enums';
  import { signup } from '$lib/api/auth';

  let form = $state({
    username: '',
    email: '',
    password: '',
    name: ''
  });
  let loading = $state(false);
  let errorMessage = $state('');

  async function handleSignup(event) {
    loading = true;
    event.preventDefault();

    try {
      const res = await signup(form);
      console.log(res);
      form.username = '';
      form.email = '';
      form.password = '';
      form.name = '';
      errorMessage = '';
    } catch (error) {
      console.log(error);
      errorMessage = error;
    } finally {
      loading = false;
    }
  }
</script>

<div class="bg-base-200 flex min-h-screen items-center justify-center">
  <div class="card bg-base-100 lg:card-side min-h-[75vh] w-full max-w-7xl shadow-xl">
    <figure class="lg:w-3/5">
      <img src="/hut.jpg" alt="hut" class="h-full w-full object-cover" />
    </figure>
    <div class="card-body lg:w-1/2">
      <h2 class="prose card-title text-accent mb-6 text-4xl font-bold">Signup to Tulz</h2>
      {#if errorMessage}
        <Alert type={AlertType.ERROR} message={errorMessage} />
      {/if}
      <form onsubmit={handleSignup} method="POST">
        <FormField
          type="text"
          labelname="Name"
          placeholder="Enter Name"
          id="name"
          bind:value={form.name}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="lucide lucide-book-user h-4 w-4 opacity-70"
            ><path d="M15 13a3 3 0 1 0-6 0" /><path
              d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20"
            /><circle cx="12" cy="8" r="2" /></svg
          >
        </FormField>

        <FormField
          type="text"
          labelname="Username"
          placeholder="Enter Username"
          id="username"
          bind:value={form.username}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="lucide lucide-user h-4 w-4 opacity-70"
          >
            <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
            <circle cx="12" cy="7" r="4" />
          </svg>
        </FormField>

        <FormField
          type="email"
          labelname="Email"
          placeholder="example@example.com"
          id="email"
          bind:value={form.email}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 16 16"
            fill="currentColor"
            class="h-4 w-4 opacity-70"
          >
            <path
              d="M2.5 3A1.5 1.5 0 0 0 1 4.5v.793c.026.009.051.02.076.032L7.674 8.51c.206.1.446.1.652 0l6.598-3.185A.755.755 0 0 1 15 5.293V4.5A1.5 1.5 0 0 0 13.5 3h-11Z"
            />
            <path
              d="M15 6.954 8.978 9.86a2.25 2.25 0 0 1-1.956 0L1 6.954V11.5A1.5 1.5 0 0 0 2.5 13h11a1.5 1.5 0 0 0 1.5-1.5V6.954Z"
            />
          </svg>
        </FormField>

        <FormField
          type="password"
          labelname="Password"
          placeholder="Enter password"
          id="password"
          bind:value={form.password}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 16 16"
            fill="currentColor"
            class="h-4 w-4 opacity-70"
          >
            <path
              fill-rule="evenodd"
              d="M14 6a4 4 0 0 1-4.899 3.899l-1.955 1.955a.5.5 0 0 1-.353.146H5v1.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-2.293a.5.5 0 0 1 .146-.353l3.955-3.955A4 4 0 1 1 14 6Zm-4-2a.75.75 0 0 0 0 1.5.5.5 0 0 1 .5.5.75.75 0 0 0 1.5 0 2 2 0 0 0-2-2Z"
              clip-rule="evenodd"
            />
          </svg>
        </FormField>

        <div class="form-control mt-10">
          <button type="submit" class="btn btn-primary">
            {#if loading}
              <span class="loading loading-spinner loading-md"></span>
            {:else}
              Signup
            {/if}
          </button>
        </div>
      </form>
      <div class="divider pt-8">OR</div>
      <div class="prose text-center">
        <p>Already have an account?</p>
        <a href="/login" class="link link-primary">Login here</a>
      </div>
    </div>
  </div>
</div>

// client/src/pages/Signup.jsx
import Axios from "../constants/api"
import { useEffect, useState } from "react"
import FormField from "../components/FormField"
import APP_NAME from "../constants/constants"
import AlertComponent from "../components/AlertComponent"


function Signup() {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [form, setForm] = useState({
    name: "",
    username: "",
    email: "",
    password: "",
  })

  const handleSubmit = (e) => {
    e.preventDefault()
    setLoading(true)
    setError(null)

    Axios.post("/user/create-account", form)
      .then(res => {
        setForm({
          name: "",
          username: "",
          email: "",
          password: ""
        })
        console.log(res)
      })
      .catch(err => {
        console.log(err.response)
        if (err.response.data) {
          // Extract the error message
          const errorMessage = err.response.data.detail || "An unknown error occurred.";
          setError(errorMessage);
        }
      })
      .finally(() => {
        setLoading(false)
      })
  }

  return (
    <>
      <div className="flex items-center justify-center min-h-screen">
        <div className="card bg-base-100 w-full sm:w-2/6 shadow-xl">
          <figure className="px-8 pt-8">
            <img
              src={`/images/caldera.jpg`}
              alt="Example"
              className="rounded-xl"
            />

          </figure>
          <div className="card-body items-center text-center">
            <h2 className="card-title">Sign up to {APP_NAME}</h2>

            <form onSubmit={handleSubmit}>
              <FormField
                name="name"
                title="Name:"
                value={form.name}
                placeholder="e.g. Carlos"
                handleTextChange={(e) => setForm({ ...form, name: e.target.value })}
              />
              <FormField
                name="username"
                title="Username:"
                value={form.username}
                placeholder="e.g. barlost"
                handleTextChange={(e) => setForm({ ...form, username: e.target.value })}
              />
              <FormField
                type="email"
                name="email"
                title="Email:"
                value={form.email}
                placeholder="user@example.com"
                handleTextChange={(e) => setForm({ ...form, email: e.target.value })}
              />
              <FormField
                type="password"
                name="password"
                title="Password:"
                value={form.password}
                handleTextChange={(e) => setForm({ ...form, password: e.target.value })}
              />

              <AlertComponent errorMessage={error} />

              <p></p>
              <div className="card-actions flex justify-center">
                <div className="flex w-full flex-col border-opacity-50 pt-2">
                  <button type="submit" className="btn btn-active">
                    {loading ? <span className="loading loading-dots loading-lg"></span> : "Create Account"}
                  </button>
                  <div className="divider">OR</div>
                  <a className="text-blue-500" href="/login">Login To Account</a>
                </div>
              </div>

            </form>
          </div>
        </div>
      </div>
    </>
  )
}

export default Signup
