// client/src/components/FormField.jsx
import React from 'react'

function FormField({ name, title, type = "text", value, placeholder, handleTextChange, otherStyles, ...props }) {
  return (
    <>
      <label className="input input-bordered flex items-center gap-2 m-4">
        {title}
        <input 
          name={name}
          type={type} 
          value={value} 
          className={`w-full text-cyan-700 text-sm ${otherStyles}`}
          placeholder={placeholder}
          onChange={handleTextChange} 
          {...props}
        />
      </label>
    </>
  )
}

export default FormField

// client/src/lib/components/FormField.svelte
<script>
	let { type, labelname, placeholder, id, value = $bindable(), children } = $props();
</script>

<div class="form-control mt-8">
	<label for={id} class="label">
		<span class="label-text">{labelname}</span>
	</label>
	<label class="input input-bordered flex items-center gap-2">
		{#if children}
			{@render children()}
		{/if}
		<input class="grow" bind:value={value} {type} {placeholder} />
	</label>
</div>
